import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');
const site = 'https://runescapedragonwilds.wiki';
const reviewed = '2026-07-18';

const shared = {
  de: {
    lang: 'de', label: 'Deutsch', home: 'Startseite', current: 'Kurzantwort', points: 'Das Wichtigste', steps: 'So gehst du weiter vor', faq: 'Häufige Fragen', related: 'Verwandte Guides',
    nav: [['Guides','/de/guides/'],['Quests','/de/quests/'],['Ressourcen','/de/resources/'],['Fähigkeiten','/de/skills-builds/'],['Problemlösungen','/de/troubleshooting/'],['Updates','/de/updates/']],
    editorial: 'Diese Seite wird redaktionell geprüft und bei Patches aktualisiert. Der Guide ist ein inoffizielles Fanprojekt und nicht mit Jagex verbunden.',
    source: 'Offizielle Neuigkeiten prüfen', sourceUrl: 'https://dragonwilds.runescape.com/news',
    suffix: ' | Dragonwilds Guide'
  },
  fr: {
    lang: 'fr', label: 'Français', home: 'Accueil', current: 'Réponse rapide', points: 'Points essentiels', steps: 'Comment continuer', faq: 'Questions fréquentes', related: 'Guides associés',
    nav: [['Guides','/fr/guides/'],['Quêtes','/fr/quests/'],['Ressources','/fr/resources/'],['Compétences','/fr/skills-builds/'],['Dépannage','/fr/troubleshooting/'],['Mises à jour','/fr/updates/']],
    editorial: 'Cette page est vérifiée éditorialement et mise à jour après les correctifs. Ce guide de fans non officiel n’est pas affilié à Jagex.',
    source: 'Consulter les actualités officielles', sourceUrl: 'https://dragonwilds.runescape.com/news',
    suffix: ' | Guide Dragonwilds'
  }
};

const pages = {
  de: [
    ['','RuneScape Dragonwilds Wiki auf Deutsch','Deutsches RuneScape-Dragonwilds-Wiki mit Guides zu Einstieg, Quests, Ressourcen, Kampf, Herstellung, Servern und aktuellen Fehlerbehebungen.','Deutscher Dragonwilds Guide','Hier findest du geprüfte Hilfen für RuneScape: Dragonwilds. Beginne mit dem Einsteiger-Guide oder wähle genau das System, die Quest oder den Fehler, bei dem du festhängst.',['Dragonwilds befindet sich im Early Access; Patchstände können Lösungen verändern.','Die wichtigsten Bereiche sind Einstieg, Quests, Ressourcen, Builds und Server.','Jeder Detailguide beantwortet zuerst die konkrete Spielerfrage.'],['Öffne für die ersten Stunden den Einsteiger-Guide.','Nutze bei einem technischen Problem den Bereich Problemlösungen.','Vergleiche bei Serverproblemen immer Client- und Serverversion.'],'Ist dies eine offizielle Wiki?','Nein. Es ist ein unabhängiges, redaktionell gepflegtes Fanprojekt.'],
    ['guides','Dragonwilds Guides auf Deutsch','Deutsche Dragonwilds-Guides für Einsteiger, Erkundung, Kampf, Herstellung, Quests, Koop und dedizierte Server – nach Spielerproblem sortiert.','Alle Dragonwilds Guides','Wähle den Guide nach deinem aktuellen Ziel: Überleben und Aufbau für den Start, Quests für konkrete Blockaden oder Problemlösungen bei Fehlern und Servern.',['Neue Spieler sollten zuerst Werkzeuge, Schutz, Nahrung und einen sicheren Stützpunkt priorisieren.','Für Fortschritt sind Ressourcenketten und passende Werkbänke wichtiger als wahlloses Sammeln.','Quest- und Patch-Guides nennen bekannte Fehler ausdrücklich.'],['Lege dein aktuelles Ziel fest.','Öffne den passenden Themen-Hub.','Prüfe vor einer Lösung den installierten Patchstand.'],'Wo sollte ich anfangen?','Im Einsteiger-Guide; danach führen interne Links zu Ressourcen, Kampf und Quests.'],
    ['beginner-guide','Dragonwilds Einsteiger-Guide','Dragonwilds Einsteiger-Guide auf Deutsch: erste Werkzeuge, Nahrung, Unterkunft, Ressourcen, Kampfvorbereitung und sinnvolle Fortschrittsreihenfolge.','Einsteiger-Guide','Sichere zuerst Nahrung, einfache Werkzeuge und einen geschützten Rückzugsort. Erkunde anschließend in kurzen Wegen und bringe Materialien regelmäßig zurück, statt alles bei einem riskanten Lauf zu tragen.',['Baue nur so groß, wie deine aktuelle Materialversorgung erlaubt.','Halte Heilung und Ausdauerreserven bereit, bevor du unbekannte Gebiete betrittst.','Verbessere Ausrüstung passend zur nächsten Region und nicht nur nach Schadenswert.'],['Sammle Holz, Stein und verlässliche Nahrung.','Errichte einen kleinen funktionalen Stützpunkt.','Stelle Werkzeuge, Heilung und erste Kampfausrüstung her.','Markiere Ressourcenwege und erweitere danach kontrolliert.'],'Kann man allein spielen?','Ja. Koop erleichtert Arbeitsteilung, aber die grundlegenden Systeme funktionieren auch solo.'],
    ['quests','Dragonwilds Quests und Lösungen','Deutsche Lösungen für Dragonwilds-Quests, Questmarker, unsichtbare Barrieren, fehlende Effekte und blockierte Abgaben.','Quests und Questprobleme','Lies zuerst den aktiven Aufgabentext und vergleiche ihn mit der Umgebung. Marker können in einzelnen bekannten Fällen falsch oder zu groß sein; starte eine Quest deshalb nicht vorschnell neu.',['Contact! kann einen ungenauen Marker oder eine unsichtbare Barriere zeigen.','Bei Beast in the Sand kann der Sand-Effekt für beitretende Spieler fehlen.','Lagra kann die Abgabe verweigern, wenn das Inventar vollständig belegt ist.'],['Prüfe Patchstand und aktives Ziel.','Schaffe einen freien Inventarplatz.','Lass im Koop den Host einen fehlenden Effekt prüfen.','Dokumentiere Zieltext und Version, bevor du einen Fehler meldest.'],'Soll ich eine blockierte Quest abbrechen?','Meist nicht. Prüfe zuerst den passenden Fehlerguide, Grafikoptionen und Inventarplatz.'],
    ['resources','Dragonwilds Ressourcen-Guide','Dragonwilds Ressourcen auf Deutsch: Materialien finden, sicher transportieren, für Rezepte planen und unnötige Sammelwege vermeiden.','Ressourcen und Materialien','Sammle mit einem konkreten Rezept oder Ausbauziel. So erkennst du, welche Ressource wirklich fehlt, und vermeidest volle Lager mit Material, das deinen nächsten Fortschritt nicht unterstützt.',['Regionen und Gefahren bestimmen, welche Ausrüstung ein Sammellauf benötigt.','Werkzeuge und Tragkapazität entscheiden über die Effizienz eines Weges.','Seltene Komponenten sollten erst verbraucht werden, wenn das Rezept zum aktuellen Patch passt.'],['Wähle Rezept oder Gebäude als Ziel.','Notiere fehlende Mengen.','Plane eine sichere Route mit Rückweg.','Lagere seltene Komponenten getrennt.'],'Warum erscheint ein Rezept nicht?','Prüfe Werkbank, Freischaltung und Patchstand; manche Rezepte wurden mit Updates verschoben oder korrigiert.'],
    ['skills-builds','Dragonwilds Fähigkeiten und Builds','Deutsche Dragonwilds-Builds und Fähigkeiten: sinnvolle Kombinationen für Kampf, Überleben, Sammeln, Solo-Spiel und Koop-Rollen.','Fähigkeiten und Builds','Ein guter Build unterstützt eine konkrete Aufgabe. Kombiniere Überlebensfähigkeit, Ausdauer und passende Schadensoptionen, statt nur einzelne Maximalwerte zu verfolgen.',['Solo-Builds brauchen verlässliche Heilung und eine sichere Ausweichoption.','Im Koop können Rollen stärker spezialisiert werden.','Sammel-Builds sparen Zeit, ersetzen aber keine Vorbereitung auf Gebietsgefahren.'],['Lege Rolle und Zielinhalt fest.','Wähle eine defensive Grundlage.','Ergänze Schaden oder Sammeltempo.','Teste Änderungen in einem bekannten Gebiet.'],'Gibt es den einen besten Build?','Nein. Der beste Build hängt von Region, Gegner, Gruppengröße und verfügbarer Ausrüstung ab.'],
    ['combat','Dragonwilds Kampf-Guide','Dragonwilds Kampf auf Deutsch: Vorbereitung, Schadensarten, Ausdauer, Blocken, Ausweichen und sichere Vorgehensweise gegen stärkere Gegner.','Kampf und Vorbereitung','Betritt einen schweren Kampf mit reparierter Ausrüstung, Heilung und einer klaren Rückzugsroute. Beobachte zuerst Angriffsmuster und verbrauche Ausdauer nicht vollständig für Schaden.',['Blocken und Ausweichen benötigen Timing und Reserven.','Widerstände und Schadensarten können wichtiger sein als ein kleiner Ausrüstungswert.','Ein sicherer Rückweg verhindert, dass ein Fehler den gesamten Sammellauf kostet.'],['Repariere und ergänze Verbrauchsgüter.','Teste Reichweite und Angriffsmuster.','Nutze kurze sichere Schadensfenster.','Ziehe dich zurück, bevor Heilung und Ausdauer ausgehen.'],'Warum verliere ich trotz besserer Waffe?','Häufig fehlen defensive Werte, Ausdauerdisziplin oder eine passende Antwort auf den Gegnertyp.'],
    ['recipes','Dragonwilds Rezepte und Herstellung','Deutscher Dragonwilds-Rezeptguide zu Werkbänken, Freischaltungen, Materialien und patchabhängigen Änderungen an Herstellungsrezepten.','Rezepte und Herstellung','Prüfe bei jedem Rezept drei Dinge: richtige Werkbank, erfüllte Freischaltung und aktueller Patch. Ein vorhandenes Material allein garantiert nicht, dass das Rezept an dieser Station erscheint.',['Fernkampfrezepte gehören nach der Stationsüberarbeitung zur Befiederungsbank.','Die unbeabsichtigte Voraussetzung für Adamantbolzen wurde mit Patch 0.12.0.4 entfernt.','Alte Screenshots können inzwischen falsche Komponenten zeigen.'],['Aktualisiere Client und Server.','Öffne die thematisch passende Werkbank.','Vergleiche Freischaltung und Materialliste.','Verbrauche seltene Teile erst nach der Prüfung.'],'Warum widersprechen sich Rezeptlisten?','Early-Access-Patches können Stationen, Voraussetzungen oder Komponenten ändern. Nutze eine datierte Quelle.'],
    ['crafting-stations','Dragonwilds Werkbänke erklärt','Dragonwilds Werkbänke auf Deutsch: welche Station für Waffen, Rüstung, Fernkampf, Verarbeitung und fortgeschrittene Rezepte zuständig ist.','Werkbänke und Stationen','Nutze die spezialisierte Station für den Gegenstandstyp. Nach Systemänderungen liegen Rezepte nicht zwingend an derselben allgemeinen Werkbank wie in älteren Guides.',['Stationszugang und Rezeptfreischaltung sind getrennte Voraussetzungen.','Dedizierte Server müssen nach Hotfixes aktualisiert werden.','Verschwindende Verarbeitungsstationen nach Neustarts wurden in 0.12.0.6 behoben.'],['Prüfe die Gegenstandskategorie.','Öffne die spezialisierte Station.','Vergleiche Server- und Clientversion.','Lade die Welt nach einem Fix neu, bevor du doppelt baust.'],'Soll ich eine verschwundene Station sofort neu bauen?','Nein. Aktualisiere und lade die Welt zuerst, da unsichtbare Kollision oder ein behobener Serverfehler vorliegen kann.'],
    ['troubleshooting','Dragonwilds Problemlösungen','Dragonwilds Problemlösungen auf Deutsch für Grafikfehler, Quests, Erfolge, Angeln, Rezepte sowie dedizierte Server und Versionsprobleme.','Problemlösungen','Aktualisiere zuerst Spiel und Server. Wähle danach den Guide für dein exaktes Symptom; allgemeines Neuinstallieren ist selten der beste erste Schritt.',['Verzerrte Bäume lassen sich laut offizieller 0.12-Hilfe durch Zurücksetzen der Engine.ini beheben.','Mehrere Questprobleme sind Anzeige- oder Markierungsfehler und kein verlorener Spielstand.','Serverprobleme entstehen nach Hotfixes häufig durch unterschiedliche Versionen.'],['Sichere Welten und individuelle Konfiguration.','Vergleiche vollständige Versionsnummern.','Wende nur die zum Symptom passende Lösung an.','Teste erneut, bevor du Spielstände löschst oder Bauwerke ersetzt.'],'Soll ich meinen Spielstand löschen?','Nein. Die dokumentierten Lösungen erfordern normalerweise kein Löschen der Welt. Erstelle vorher immer eine Sicherung.'],
    ['dedicated-servers','Dragonwilds Dedicated Server Guide','Dragonwilds Dedicated Server auf Deutsch: Installation, RAM, UDP-Port 7777, Konfiguration, Sichtbarkeit, Updates, Backups und Welttransfer.','Dedizierte Server','Installiere das kostenlose Serverprodukt, trage Owner-ID, Servername, Weltname und Admin-Passwort ein und halte Server sowie Clients exakt auf demselben Build.',['Benötigt werden 64-Bit-Windows oder Linux und etwa 2 GB Basis-RAM plus 1 GB pro Spieler.','Der erste Server verwendet UDP 7777; weitere Instanzen beginnen bei 7778.','Bis zu sechs Spieler werden unterstützt.'],['Stoppe den Server vor Konfigurationsänderungen.','Sichere den Ordner Saved/Savegames.','Öffne den benötigten UDP-Port in Firewall und Router.','Prüfe die Version oben im Log.'],'Warum erscheint mein Server nicht?','Prüfe Versionsgleichheit, exakte Großschreibung des Weltnamens, Pflichtfelder und anschließend das Serverlog.'],
    ['map','Dragonwilds Karte und Regionen','Deutscher Dragonwilds-Kartenguide zu Regionen, Routenplanung, Gefahren, Ressourcenwegen und bekannten Problemen mit Questmarkern.','Karte und Erkundung','Plane Reisen nach Ziel, Gefahr und Rückweg. Ein Kartenmarker ist eine Hilfe, ersetzt aber bei bekannten Questfehlern nicht Zieltext, Landmarken und sichtbare Wege.',['Nimm nur die für Region und Aufgabe benötigte Ausrüstung mit.','Markiere ergiebige Ressourcenrouten und sichere Zwischenpunkte.','Bei Contact! kann Position oder Größe des Questmarkers falsch sein.'],['Definiere Ziel und Rückkehrpunkt.','Prüfe Nahrung, Heilung und Werkzeug.','Folge Landmarken statt blind dem Rand eines fehlerhaften Markers.','Notiere sichere Abkürzungen für spätere Läufe.'],'Ist jeder Marker exakt?','Nein. Einzelne Questmarker sind als fehlerhaft dokumentiert; nutze dann Zieltext und Umgebungsmerkmale.'],
    ['fishing','Dragonwilds Angeln Guide','Dragonwilds Angeln auf Deutsch: Angelstellen erkennen, Ausrüstung prüfen und nicht funktionierende Stellen in Fellhollow oder Brynmoor beheben.','Angeln','Nicht nutzbare Angelstellen in Fellhollow und Brynmoor wurden mit Patch 0.12.0.4 behoben. Aktualisiere Client und Server und betrete das Gebiet anschließend neu.',['Nicht jede Wasserbewegung ist automatisch eine gültige Angelstelle.','Koop-Spieler und Server müssen denselben Build verwenden.','Ein alter Interaktionsfehler ist von falscher Ausrüstung zu unterscheiden.'],['Prüfe Version und Ausrüstung.','Aktualisiere den dedizierten Server.','Verlasse das Gebiet und kehre zurück.','Teste eine eindeutig gültige Angelstelle.'],'Warum reagiert die Stelle weiterhin nicht?','Prüfe, ob es wirklich eine Angelstelle ist und ob Methode sowie Ausrüstung zum Spot passen.'],
    ['updates','Dragonwilds Updates und Patchnotes','Deutsche Übersicht wichtiger Dragonwilds-Updates, Hotfixes, behobener Fehler und Änderungen, die Quests, Rezepte oder Server-Guides beeinflussen.','Updates und Patchstände','Nutze immer die vollständige Versionsnummer. Kleine Hotfixes innerhalb von 0.12 können Rezepte, Erfolge, Angelstellen oder Serverfehler gezielt verändern.',['0.12.0.4 korrigierte unter anderem Angelstellen und die Adamantbolzen-Voraussetzung.','0.12.0.6 behob verschwindende Stationen und den Splinter-Serverabsturz.','Alte Guides benötigen deshalb einen sichtbaren Prüfstatus.'],['Vergleiche Client- und Serverbuild.','Lies die Änderung für dein konkretes Problem.','Sichere Serverwelten vor Updates.','Teste die bisher fehlerhafte Aktion erneut.'],'Warum ist die Unterversion wichtig?','Weil ein Server auf 0.12.0.1 nicht dieselben Korrekturen wie 0.12.0.6 enthält.'],
    ['faq','Dragonwilds FAQ auf Deutsch','Häufige Fragen zu RuneScape Dragonwilds: Early Access, Solo und Koop, Spielerzahl, Sprachen, Plattformen, Server und Guide-Aktualität.','Häufige Fragen','Dragonwilds ist ein Early-Access-Survival-Abenteuer für Solo-Spiel und Online-Koop. Dedizierte Server unterstützen bis zu sechs Spieler; Inhalte und Plattformpläne können sich weiterentwickeln.',['Steam führt zehn unterstützte Oberflächen- und Untertitelsprachen, darunter Deutsch und Französisch.','Die veröffentlichten Sprachangaben weisen keine vollständige Sprachausgabe aus.','Für aktuelle Fehler ist die genaue Patchnummer entscheidend.'],['Prüfe für Kauf- und Plattformfragen die offizielle Store-Seite.','Nutze für Spielfragen den thematischen Guide.','Vergleiche bei Bugs die vollständige Version.'],'Hat Dragonwilds deutsche Texte?','Ja. Deutsch wird für Oberfläche und Untertitel unterstützt; eine vollständige deutsche Vertonung ist nicht ausgewiesen.'],
    ['about','Über dieses Dragonwilds Wiki','Über das deutsche Dragonwilds Field Guide: redaktionelle Regeln, Quellen, Patchprüfung, Korrekturen und Kennzeichnung als inoffizielles Fanprojekt.','Über dieses Wiki','Wir veröffentlichen nur Seiten, die eine konkrete Spielerfrage beantworten. Patchabhängige Aussagen erhalten einen Prüfstatus; unbestätigte Gegenstände oder erfundene Inhalte werden nicht als Fakten ausgegeben.',['Offizielle Patchnotes und Serverdokumentation sind Primärquellen.','Bekannte Fehler werden von dauerhaften Spielmechaniken getrennt.','Korrekturen werden in betroffenen Guides nachvollziehbar eingearbeitet.'],['Prüfe das Datum einer patchabhängigen Lösung.','Vergleiche bei Unsicherheit die verlinkte offizielle Quelle.','Melde Widersprüche mit Version und betroffenem Ziel.'],'Ist die Seite mit Jagex verbunden?','Nein. Dragonwilds Field Guide ist ein unabhängiges Fanprojekt.']
  ],
  fr: [
    ['','Wiki RuneScape Dragonwilds en français','Wiki français de RuneScape Dragonwilds avec guides de début, quêtes, ressources, combat, artisanat, serveurs et solutions aux bugs actuels.','Guide Dragonwilds en français','Retrouvez des réponses vérifiées pour RuneScape: Dragonwilds. Commencez par le guide du débutant ou choisissez précisément le système, la quête ou le problème qui bloque votre progression.',['Dragonwilds est en accès anticipé : un correctif peut modifier une solution.','Les rubriques principales couvrent début, quêtes, ressources, builds et serveurs.','Chaque guide détaillé donne d’abord une réponse directe.'],['Ouvrez le guide du débutant pour vos premières heures.','Utilisez le dépannage pour un souci technique.','Pour un serveur, comparez toujours les versions du client et du serveur.'],'Ce wiki est-il officiel ?','Non. Il s’agit d’un projet de fans indépendant et vérifié éditorialement.'],
    ['guides','Guides Dragonwilds en français','Guides Dragonwilds en français pour débutants, exploration, combat, artisanat, quêtes, coopération et serveurs dédiés, classés par besoin.','Tous les guides Dragonwilds','Choisissez selon votre objectif actuel : survie et construction pour commencer, quêtes pour un blocage précis, ou dépannage pour les bugs et serveurs.',['Les nouveaux joueurs doivent privilégier outils, protection, nourriture et abri sûr.','Les chaînes de ressources et les ateliers adaptés structurent la progression.','Les guides de quêtes et correctifs signalent clairement les bugs connus.'],['Définissez votre objectif immédiat.','Ouvrez la rubrique correspondante.','Vérifiez la version installée avant d’appliquer une solution.'],'Par où commencer ?','Par le guide du débutant, puis les liens internes vers ressources, combat et quêtes.'],
    ['beginner-guide','Guide du débutant Dragonwilds','Guide du débutant Dragonwilds en français : premiers outils, nourriture, abri, ressources, préparation au combat et progression efficace.','Guide du débutant','Sécurisez d’abord nourriture, outils simples et refuge protégé. Explorez ensuite par trajets courts et rapportez régulièrement les matériaux au lieu de tout risquer lors d’une longue sortie.',['Construisez selon vos ressources actuelles, sans agrandir trop tôt.','Gardez soins et endurance avant d’entrer dans une région inconnue.','Améliorez l’équipement selon la prochaine zone plutôt que le seul score de dégâts.'],['Collectez bois, pierre et nourriture fiable.','Montez une petite base fonctionnelle.','Fabriquez outils, soins et premier équipement de combat.','Repérez les routes de ressources avant de vous étendre.'],'Peut-on jouer en solo ?','Oui. La coopération facilite la répartition des tâches, mais les systèmes de base fonctionnent aussi en solo.'],
    ['quests','Quêtes Dragonwilds et solutions','Solutions françaises pour les quêtes Dragonwilds, marqueurs erronés, barrières invisibles, effets absents et remises d’objets bloquées.','Quêtes et blocages','Relisez l’objectif actif et comparez-le au terrain. Certains marqueurs connus sont mal placés ou trop larges ; ne recommencez donc pas une quête immédiatement.',['Contact! peut afficher un marqueur incorrect ou une barrière invisible.','Dans Beast in the Sand, la traînée de sable peut manquer chez les joueurs clients.','Lagra peut refuser la remise si l’inventaire est plein.'],['Vérifiez le correctif et l’objectif actif.','Libérez une case d’inventaire.','En coopération, demandez à l’hôte de vérifier l’effet absent.','Notez objectif et version avant de signaler le bug.'],'Faut-il abandonner une quête bloquée ?','Généralement non. Consultez d’abord le guide du bug, les options graphiques et l’espace d’inventaire.'],
    ['resources','Ressources Dragonwilds','Guide français des ressources Dragonwilds : trouver les matériaux, les transporter, préparer les recettes et réduire les trajets inutiles.','Ressources et matériaux','Collectez avec une recette ou une amélioration précise en tête. Vous saurez ainsi ce qui manque vraiment et éviterez de remplir les coffres de matériaux inutiles à la prochaine étape.',['La région et ses dangers déterminent l’équipement nécessaire.','Outils et capacité de transport influencent le rendement du trajet.','Ne dépensez un composant rare qu’après avoir vérifié la recette du correctif actuel.'],['Choisissez une recette ou un bâtiment cible.','Listez les quantités manquantes.','Planifiez une route sûre avec retour.','Stockez séparément les composants rares.'],'Pourquoi une recette n’apparaît-elle pas ?','Vérifiez atelier, déblocage et version : des recettes ont été déplacées ou corrigées.'],
    ['skills-builds','Compétences et builds Dragonwilds','Builds Dragonwilds en français pour combat, survie, collecte, solo et rôles coopératifs, avec choix adaptés à chaque objectif.','Compétences et builds','Un bon build répond à une tâche précise. Associez survie, endurance et dégâts appropriés plutôt que de maximiser une seule valeur.',['Un build solo a besoin de soins fiables et d’une option de repli.','En coopération, les rôles peuvent être plus spécialisés.','Un build de collecte accélère les trajets mais ne remplace pas la préparation aux dangers.'],['Définissez rôle et contenu visé.','Choisissez une base défensive.','Ajoutez dégâts ou vitesse de collecte.','Testez les changements dans une zone connue.'],'Existe-t-il un meilleur build unique ?','Non. Il dépend de la région, de l’ennemi, du groupe et de votre équipement.'],
    ['combat','Guide de combat Dragonwilds','Combat Dragonwilds en français : préparation, types de dégâts, endurance, parade, esquive et méthode sûre contre les ennemis puissants.','Combat et préparation','Entrez dans un combat difficile avec équipement réparé, soins disponibles et voie de repli claire. Observez les attaques avant de dépenser toute l’endurance pour infliger des dégâts.',['Parade et esquive exigent du timing et une réserve d’endurance.','Résistances et types de dégâts peuvent compter plus qu’un petit gain d’équipement.','Une route de sortie sûre protège les ressources de votre expédition.'],['Réparez et complétez les consommables.','Testez portée et séquences d’attaque.','Frappez pendant les fenêtres sûres.','Reculez avant d’épuiser soins et endurance.'],'Pourquoi perdre avec une meilleure arme ?','Il manque souvent défense, gestion d’endurance ou réponse adaptée au type d’ennemi.'],
    ['recipes','Recettes et artisanat Dragonwilds','Guide français des recettes Dragonwilds : ateliers, déblocages, matériaux et changements de fabrication liés aux correctifs.','Recettes et artisanat','Pour chaque recette, vérifiez l’atelier, le déblocage et la version. Posséder le matériau ne garantit pas que la recette apparaisse sur cette station.',['Après la réorganisation, les recettes à distance utilisent l’établi d’empennage.','Le prérequis involontaire des carreaux d’adamant a été retiré en 0.12.0.4.','D’anciennes captures peuvent montrer des composants désormais incorrects.'],['Mettez client et serveur à jour.','Ouvrez l’atelier spécialisé.','Comparez déblocage et liste de matériaux.','Ne consommez un objet rare qu’après vérification.'],'Pourquoi les listes de recettes se contredisent-elles ?','Les mises à jour peuvent changer atelier, prérequis ou composant. Consultez une source datée.'],
    ['crafting-stations','Ateliers Dragonwilds expliqués','Ateliers Dragonwilds en français : stations pour armes, armures, distance, transformation et recettes avancées.','Ateliers et stations','Utilisez la station spécialisée pour le type d’objet. Après une mise à jour, une recette peut ne plus se trouver sur l’ancien atelier général.',['Accès à la station et déblocage de recette sont deux conditions distinctes.','Les serveurs dédiés doivent être actualisés après les correctifs.','La disparition de stations après redémarrage a été corrigée en 0.12.0.6.'],['Identifiez la catégorie de l’objet.','Ouvrez la station spécialisée.','Comparez versions serveur et client.','Rechargez le monde avant de reconstruire en double.'],'Faut-il reconstruire immédiatement une station disparue ?','Non. Mettez à jour et rechargez d’abord, car une collision invisible peut subsister.'],
    ['troubleshooting','Dépannage Dragonwilds','Dépannage Dragonwilds en français pour graphismes, quêtes, succès, pêche, recettes, serveurs dédiés et versions incompatibles.','Dépannage','Mettez d’abord le jeu et le serveur à jour. Choisissez ensuite la solution correspondant exactement au symptôme ; une réinstallation complète est rarement la meilleure première action.',['Les arbres déformés peuvent être corrigés en réinitialisant Engine.ini selon l’aide officielle 0.12.','Plusieurs soucis de quête sont des erreurs d’affichage, pas une sauvegarde perdue.','Après un hotfix, les serveurs échouent souvent à cause de versions différentes.'],['Sauvegardez mondes et configuration personnalisée.','Comparez les numéros de version complets.','Appliquez uniquement la solution liée au symptôme.','Retestez avant de supprimer une sauvegarde ou reconstruire.'],'Dois-je supprimer ma sauvegarde ?','Non. Les solutions documentées ne l’exigent normalement pas. Faites toujours une copie avant toute manipulation.'],
    ['dedicated-servers','Guide serveur dédié Dragonwilds','Serveur dédié Dragonwilds en français : installation, RAM, port UDP 7777, configuration, visibilité, mises à jour, sauvegardes et transfert.','Serveurs dédiés','Installez le produit serveur gratuit, renseignez identifiant propriétaire, nom du serveur, monde par défaut et mot de passe administrateur, puis alignez exactement toutes les versions.',['Système Windows ou Linux 64 bits avec environ 2 Go de base plus 1 Go par joueur.','Le premier serveur utilise UDP 7777 ; les suivants commencent à 7778.','Le maximum publié est de six joueurs.'],['Arrêtez le serveur avant de modifier la configuration.','Sauvegardez Saved/Savegames.','Ouvrez le port UDP dans pare-feu et routeur.','Contrôlez la version en haut du journal.'],'Pourquoi le serveur n’apparaît-il pas ?','Vérifiez version, casse exacte du nom du monde, champs obligatoires puis journal du serveur.'],
    ['map','Carte et régions Dragonwilds','Guide français de la carte Dragonwilds : régions, routes, dangers, circuits de ressources et problèmes connus de marqueurs de quête.','Carte et exploration','Planifiez chaque voyage selon objectif, danger et retour. Un marqueur aide, mais en cas de bug connu, le texte de quête et les repères du terrain restent prioritaires.',['Emportez seulement l’équipement utile à la région et à la tâche.','Repérez les routes de ressources et les étapes sûres.','Dans Contact!, la position ou la taille du marqueur peut être erronée.'],['Définissez objectif et point de retour.','Vérifiez nourriture, soins et outil.','Suivez les repères plutôt que le bord d’un marqueur défectueux.','Notez les raccourcis sûrs.'],'Tous les marqueurs sont-ils exacts ?','Non. Certains marqueurs de quête sont documentés comme incorrects.'],
    ['fishing','Guide de pêche Dragonwilds','Pêche Dragonwilds en français : reconnaître les emplacements, vérifier l’équipement et corriger les spots inutilisables de Fellhollow ou Brynmoor.','Pêche','Les emplacements inutilisables de Fellhollow et Brynmoor ont été corrigés en 0.12.0.4. Actualisez client et serveur, puis revenez dans la zone.',['Toute animation d’eau n’est pas forcément un spot valide.','Les joueurs coopératifs et le serveur doivent utiliser le même build.','Distinguez ancien bug d’interaction et mauvais équipement.'],['Vérifiez version et matériel.','Mettez le serveur dédié à jour.','Quittez puis rechargez la zone.','Testez un emplacement clairement valide.'],'Pourquoi le spot ne répond-il toujours pas ?','Vérifiez qu’il s’agit bien d’un spot et que méthode et équipement lui correspondent.'],
    ['updates','Mises à jour Dragonwilds','Résumé français des mises à jour Dragonwilds, hotfixes, bugs corrigés et changements affectant quêtes, recettes ou serveurs.','Mises à jour et versions','Utilisez toujours le numéro de version complet. De petits correctifs 0.12 peuvent modifier recettes, succès, pêche ou stabilité des serveurs.',['La 0.12.0.4 a notamment corrigé pêche et prérequis des carreaux d’adamant.','La 0.12.0.6 a corrigé stations disparues et crash serveur Splinter.','Les anciens guides doivent donc afficher une date de vérification.'],['Comparez builds client et serveur.','Lisez le changement lié à votre problème.','Sauvegardez le monde avant mise à jour.','Retestez l’action auparavant défectueuse.'],'Pourquoi la sous-version compte-t-elle ?','Un serveur 0.12.0.1 ne contient pas les mêmes corrections qu’un 0.12.0.6.'],
    ['faq','FAQ Dragonwilds en français','Questions fréquentes sur RuneScape Dragonwilds : accès anticipé, solo, coopération, joueurs, langues, plateformes, serveurs et actualité des guides.','Questions fréquentes','Dragonwilds est une aventure de survie en accès anticipé jouable en solo et en coopération en ligne. Les serveurs dédiés accueillent jusqu’à six joueurs.',['Steam indique dix langues d’interface et de sous-titres, dont français et allemand.','Aucune langue n’est indiquée avec doublage intégral.','Pour un bug, le numéro exact du correctif est essentiel.'],['Consultez la boutique officielle pour achat et plateforme.','Utilisez le guide thématique pour le gameplay.','Comparez la version complète pour les bugs.'],'Dragonwilds contient-il des textes français ?','Oui. Le français est pris en charge pour interface et sous-titres, sans doublage intégral annoncé.'],
    ['about','À propos de ce wiki Dragonwilds','À propos du Dragonwilds Field Guide français : règles éditoriales, sources, vérification des correctifs et statut de projet de fans.','À propos de ce wiki','Nous publions uniquement des pages répondant à une question concrète. Les informations liées aux correctifs sont datées ; les objets non confirmés ne sont pas présentés comme des faits.',['Les notes officielles et la documentation serveur sont prioritaires.','Les bugs temporaires sont séparés des mécaniques durables.','Les corrections sont intégrées aux guides concernés.'],['Vérifiez la date d’une solution dépendante du patch.','Comparez la source officielle liée en cas de doute.','Signalez une contradiction avec version et objectif concerné.'],'Le site est-il affilié à Jagex ?','Non. Dragonwilds Field Guide est un projet de fans indépendant.']
  ]
};

function esc(v){return v.replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;')}
function route(lang,slug){return `/${lang}/${slug ? `${slug}/` : ''}`}
function render(lang,p){
  const l=shared[lang], [slug,title,description,h1,quick,points,steps,q,a]=p;
  const url=`${site}${route(lang,slug)}`;
  const en=`${site}/${slug ? `${slug}/` : ''}`;
  const alt=lang==='de'?`fr`:`de`;
  const hasAlt=pages[alt].some(x=>x[0]===slug);
  const alternates=`<link rel="alternate" hreflang="en" href="${en}"><link rel="alternate" hreflang="${lang}" href="${url}">${hasAlt?`<link rel="alternate" hreflang="${alt}" href="${site}${route(alt,slug)}">`:''}<link rel="alternate" hreflang="x-default" href="${en}">`;
  const schema={'@context':'https://schema.org','@graph':[{'@type':'Article',headline:h1,description,inLanguage:lang,dateModified:reviewed,mainEntityOfPage:url,author:{'@type':'Organization',name:'Dragonwilds Field Guide'}},{'@type':'FAQPage',mainEntity:[{'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}]},{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:l.home,item:`${site}/${lang}/`},{'@type':'ListItem',position:2,name:h1,item:url}]}]};
  const nav=l.nav.map(([n,u])=>`<a href="${u}">${n}</a>`).join('');
  const langs=`<nav class="language-switcher" aria-label="Language"><a href="${slug?`/${slug}/`:'/'}" hreflang="en">EN</a><a href="${route('de',slug)}" hreflang="de"${lang==='de'?' aria-current="page"':''}>DE</a><a href="${route('fr',slug)}" hreflang="fr"${lang==='fr'?' aria-current="page"':''}>FR</a></nav>`;
  return `<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title+l.suffix)}</title><meta name="description" content="${esc(description)}"><meta name="robots" content="index, follow, max-image-preview:large"><link rel="canonical" href="${url}">${alternates}<meta property="og:type" content="article"><meta property="og:title" content="${esc(h1)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${url}"><meta property="og:locale" content="${lang==='de'?'de_DE':'fr_FR'}"><link rel="icon" href="/favicon.ico"><link rel="stylesheet" href="/styles.css"><script type="application/ld+json">${JSON.stringify(schema)}</script></head><body><header class="site-header"><a class="brand" href="/${lang}/"><span class="brand-mark">DW</span><span>Dragonwilds Field Guide</span></a><nav aria-label="Navigation">${nav}</nav>${langs}</header><main class="page-main"><article><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/${lang}/">${l.home}</a><span>›</span><span>${h1}</span></nav><p class="eyebrow">${l.label}</p><h1>${h1}</h1><section class="quick-answer"><h2>${l.current}</h2><p><strong>${quick}</strong></p></section><section class="content-panel"><h2>${l.points}</h2><ul>${points.map(x=>`<li>${x}</li>`).join('')}</ul></section><section class="content-panel"><h2>${l.steps}</h2><ol>${steps.map(x=>`<li>${x}</li>`).join('')}</ol></section><section class="content-panel"><h2>${l.faq}</h2><h3>${q}</h3><p>${a}</p></section><aside class="source-box"><h2>Stand ${reviewed}</h2><p>${l.editorial}</p><p><a href="${l.sourceUrl}" rel="noopener noreferrer">${l.source}</a></p></aside><section class="content-panel"><h2>${l.related}</h2><ul><li><a href="/${lang}/guides/">${l.nav[0][0]}</a></li><li><a href="/${lang}/faq/">FAQ</a></li><li><a href="/${lang}/updates/">${l.nav[5][0]}</a></li></ul></section></article></main><footer class="site-footer"><p><strong>Dragonwilds Field Guide</strong> · ${l.editorial}</p><p><a href="/${lang}/about/">Editorial</a> · <a href="/sitemap.xml">Sitemap</a></p></footer></body></html>`;
}

for(const lang of Object.keys(pages)) for(const p of pages[lang]) { const f=path.join(root,lang,p[0],'index.html'); fs.mkdirSync(path.dirname(f),{recursive:true}); fs.writeFileSync(f,render(lang,p)); }

// Add alternates to English equivalents only where a real translated page exists.
for(const p of pages.de){ const slug=p[0], f=path.join(root,slug,'index.html'); if(!fs.existsSync(f)) continue; let h=fs.readFileSync(f,'utf8'); h=h.replace(/<link rel="alternate" hreflang="(?:de|fr|en|x-default)"[^>]*>/g,''); const en=`${site}/${slug?`${slug}/`:''}`; const tags=`<link rel="alternate" hreflang="en" href="${en}"><link rel="alternate" hreflang="de" href="${site}${route('de',slug)}"><link rel="alternate" hreflang="fr" href="${site}${route('fr',slug)}"><link rel="alternate" hreflang="x-default" href="${en}">`; h=h.replace('</head>',`${tags}</head>`); fs.writeFileSync(f,h); }

// Rebuild a multilingual sitemap from canonical, indexable HTML.
function walk(d){return fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)])}
const urls=[]; for(const f of walk(root).filter(x=>x.endsWith('index.html'))){const h=fs.readFileSync(f,'utf8');if(/name="robots"\s+content="[^"]*noindex/i.test(h))continue;const c=h.match(/<link\s+rel="canonical"\s+href="([^"]+)"/i)?.[1];if(c?.startsWith(`${site}/`))urls.push(c)}
urls.sort((a,b)=>a.localeCompare(b)); fs.writeFileSync(path.join(root,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map(u=>`  <url><loc>${u}</loc><lastmod>${reviewed}</lastmod></url>`).join('\n')}\n</urlset>\n`);
console.log(`Generated ${pages.de.length} German and ${pages.fr.length} French pages; sitemap contains ${urls.length} URLs.`);
